# Generated by Django 4.0.2 on 2022-02-18 09:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position_category',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='player',
            index=django.contrib.postgres.indexes.HashIndex(fields=['position'], name='player_positio_9bde1f_hash'),
        ),
    ]
